version: '3'
services:
  ##########
  # Django #
  ##########
  web:
    build: .
    network_mode: host
    restart: always
    command: python manage.py runserver # gunicorn aaaimxadmin.wsgi --log-file -
    volumes:
        - .:/usr/src/app/
    ports:
        - "8000:8000"
    env_file: .env
    depends_on:
      - db

  ############
  # Postgres #
  ############
  db:
    image: postgres:12.0-alpine
    ports:
      - '5435:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.postgres

volumes:
  postgres_data:

