version: '3'
services:
  ###
  # services
  ###
  web:
    build: .
    network_mode: host
    command: gunicorn aaaimxadmin.wsgi --log-file -
    volumes:
        - .:/app
    ports:
        - "8000:8000"
    env_file: .env
    tty: true
    stdin_open: true